### ISSUE TITLE
Not able to build the contract

### ISSUE THREAD

**Issue by Dishant1997** [EOSArgentina/evolutiondex#7]
I am not able to able to build the contract, 
version specification:
Eosio 2.0.7
Eosio.Cdt 1.7.0
Eosio.Contract 1.9.X

Getting this kind of error
```
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/evolutiondex.cpp.o: undefined symbol: evolution::evolutiondex::add_balance(eosio::name const&, eosio::asset const&, eosio::name const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/evolutiondex.cpp.o: undefined symbol: evolution::evolutiondex::sub_balance(eosio::name const&, eosio::asset const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/evolutiondex.cpp.o: undefined symbol: evolution::evolutiondex::transfer(eosio::name const&, eosio::name const&, eosio::asset const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/evolutiondex.cpp.o: undefined symbol: evolution::evolutiondex::open(eosio::name const&, eosio::symbol const&, eosio::name const&)
/usr/local/eosio.cdt/bin/wasm-ld: error: /tmp/evolutiondex.cpp.o: undefined symbol: evolution::evolutiondex::close(eosio::name const&, eosio::symbol const&)
```

I have tried different ways
1. created the skeleton for eveolutiondex contract with 
```eosio-init -project-PROJECT_NAME```
and 
2. ```eosio-cpp -o evolutiondex.wasm evolutiondex.cpp --abigen -I.```

getting the mentioned error.

Please help!!

**Comment by sergioyuhjtman** [comment]
Some functions are defined in the file token_functions.cpp. Try with
`eosio-cpp evolutiondex.cpp token_functions.cpp -o evolutiondex.wasm --abigen`

**Comment by Dishant1997** [comment]
> Some functions are defined in the file token_functions.cpp. Try with
> `eosio-cpp evolutiondex.cpp token_functions.cpp -o evolutiondex.wasm --abigen`

It worked! Thanks a lot.
